project:
    resource: "@projectBundle/Resources/config/routing.yml"
    prefix:   /

profile:
    resource: "@profileBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@userBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
