<?php

namespace Proxies\__CG__\userBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \userBundle\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'userBundle\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'userBundle\\Entity\\Client' . "\0" . 'rsocial', '' . "\0" . 'userBundle\\Entity\\Client' . "\0" . 'adr', '' . "\0" . 'userBundle\\Entity\\Client' . "\0" . 'tel', '' . "\0" . 'userBundle\\Entity\\Client' . "\0" . 'email', '' . "\0" . 'userBundle\\Entity\\Client' . "\0" . 'act', '' . "\0" . 'userBundle\\Entity\\Client' . "\0" . 'rep');
        }

        return array('__isInitialized__', '' . "\0" . 'userBundle\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'userBundle\\Entity\\Client' . "\0" . 'rsocial', '' . "\0" . 'userBundle\\Entity\\Client' . "\0" . 'adr', '' . "\0" . 'userBundle\\Entity\\Client' . "\0" . 'tel', '' . "\0" . 'userBundle\\Entity\\Client' . "\0" . 'email', '' . "\0" . 'userBundle\\Entity\\Client' . "\0" . 'act', '' . "\0" . 'userBundle\\Entity\\Client' . "\0" . 'rep');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRsocial($rsocial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRsocial', array($rsocial));

        return parent::setRsocial($rsocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getRsocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRsocial', array());

        return parent::getRsocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdr($adr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdr', array($adr));

        return parent::setAdr($adr);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdr', array());

        return parent::getAdr();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', array($tel));

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', array());

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setAct($act)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAct', array($act));

        return parent::setAct($act);
    }

    /**
     * {@inheritDoc}
     */
    public function getAct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAct', array());

        return parent::getAct();
    }

    /**
     * {@inheritDoc}
     */
    public function setRep(\userBundle\Entity\User $rep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRep', array($rep));

        return parent::setRep($rep);
    }

    /**
     * {@inheritDoc}
     */
    public function getRep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRep', array());

        return parent::getRep();
    }

}
