<?php

namespace projectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BesoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BesoinRepository extends EntityRepository
{
}
