<?php

namespace projectBundle\Entity;

use Doctrine\ORM\EntityRepository;
use userBundle\Entity\User;
/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends EntityRepository
{
    
    public function findByUserId($user) {
        
      
    
  }
    
    
    public function findChef($type)
{
 

}
    
}
