<?php

namespace projectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VersionBesoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionBesoinRepository extends EntityRepository
{
}
